#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
# Important for starting Gradle without the wrapper jar.
#
APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")
DIRNAME=$(dirname "$0")
exec "$DIRNAME/gradle/wrapper/gradle-wrapper.jar" "$@" 2>/dev/null || exec gradle "$@"
